version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: tic4902_db
    ports:
      # Exposes Postgres on your host machine at the port in .env (default 5432)
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: TIC4902_DB
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d TIC4902_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:
