apiVersion: v1
kind: Secret
metadata:
  name: postgres-cluster-pguser-nodejs
  namespace: tic4902
  labels:
    postgres-operator.crunchydata.com/cluster: postgres-cluster
    postgres-operator.crunchydata.com/pguser: nodejs
type: Opaque
stringData:
  password: nodejs-dev
