apiVersion: v1
kind: Secret
metadata:
  name: postgres-cluster-pguser-postgres
  namespace: tic4902
  labels:
    postgres-operator.crunchydata.com/cluster: postgres-cluster
    postgres-operator.crunchydata.com/pguser: postgres
type: Opaque
stringData:
  password: postgres-dev
