import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

// Generated by shadcn/ui 
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function formatDate(iso: string, monthStyle: 'short' | 'long' = 'short') {
  return new Date(iso).toLocaleString(undefined, {
    year: 'numeric', month: monthStyle, day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}

export function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`
}