import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

// Generated by shadcn/ui 
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function formatDate(iso: string, monthStyle: 'short' | 'long' = 'short') {
  return new Date(iso).toLocaleString(undefined, {
    year: 'numeric', month: monthStyle, day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}
